### ISSUE TITLE
"Warning: remote port forwarding failed" with the demo instance

### ISSUE THREAD

**Issue by snowwm** [boringproxy/boringproxy#93] opened 2021-08-12 08:12 UTC
I have set up a tunnel on https://bpdemo.brng.pro (with "Allow External TCP" checked):

    snowwm.bpdemo.brng.pro:35849 -> any -> 127.0.0.1:1080

Then I try to connect using ssh:

    ssh -v -i /home/snowwm/Desktop/id_rsa -NR 127.0.0.1:35849:127.0.0.1:1080 demo@bpdemo.brng.pro

but it says

    debug1: Remote: port forwarding refused
    debug1: remote forward failure for: listen 127.0.0.1:35849, connect 127.0.0.1:1080
    Warning: remote port forwarding failed for listen port 35849

Am I doing something wrong or your demo service doesn't support plain ssh connections?
(I just wanted to give it a try before self-hosting.)

**Comment by anderspitman** [comment] 2021-08-13 16:31
Hi @snowwm, I was able to reproduce the same behavior. During debugging I restarted the boringproxy server and it seems to be working for me now :man_shrugging:. Can you confirm whether it works for you?

**Comment by snowwm** [comment] 2021-08-13 18:33
Nope, still the same error :disappointed:

**Comment by anderspitman** [comment] 2021-12-03 23:30
@snowwm just FWI I'm closing down the demo server. I noticed it's been flagged which probably means people have been using it for spam, phishing attacks, etc. Sadly this is what usually happens with free services like this.

**Closed by anderspitman** 2021-12-03 23:30 UTC

**Comment by snowwm** [comment] 2021-12-04 08:02
@anderspitman yeah, I understand this decision. Sucks to live in a world where everything good is abused.
