### ISSUE TITLE
boringproxy vs ngrok

### ISSUE THREAD

**Issue by voarsh2** [boringproxy/boringproxy#18] opened 2020-11-22 21:26 UTC
Observations:

CapRover needs reverserproxy.
*.example.com loads: port 80, always a wildcard, each installation is subdomain
CapRover also uses port 3000 for admin panel.

Suitable NGROK configuration that works with CapRover:

tunnels:
  ljnexmo:
    addr: "127.0.0.1:80"
    hostname: test2.example.com
    proto: http
  ljnexmo2:
    addr: "127.0.0.1:80"
    hostname: test.example.com
    proto: http
  ljnexmo3:
    addr: "127.0.0.1:3000"
    hostname: captain.example.com
    proto: http

I had significant issues with CapRover and BoringProxy: 
https://github.com/caprover/caprover/issues/901

Seems the reverse proxy or lack of, is a big problem for boringproxy and the wildcards.

@anderspitman you said you had other comments?

**Comment by anderspitman** [comment] 2020-11-22 21:46
The long term plan is for boringproxy to be a suitable replacement for ngrok for most use cases.

You say you need wildcards for CapRover, but it doesn't look like you're using wildcards in that ngrok config?

As for needing a reverse proxy, boringproxy is a reverse proxy, albeit a simple one that is likely still missing important features.

**Comment by voarsh2** [comment] 2020-11-22 22:43
> As for needing a reverse proxy, boringproxy is a reverse proxy, albeit a simple one that is likely still missing important features.

The Author of CapRover said boringproxy wasn't right for it.


> The long term plan is for boringproxy to be a suitable replacement for ngrok for most use cases.

Is there a roadmap for things NGROK has that boringproxy doesn't have?

> u say you need wildcards for CapRover, but it doesn't look like you're using wildcards in that ngrok config?

I missed the bit where I have to run that configuration, plus an extra terminal with wildcard.
For some reason NGROK doesn't support wildcards in the configuration.

**Comment by anderspitman** [comment] 2020-11-23 03:50
> The Author of CapRover said boringproxy wasn't right for it.

I scanned through the thread. I don't think the author is familiar with how boringproxy works. They didn't provide a technical reason why it shouldn't work.


> Is there a roadmap for things NGROK has that boringproxy doesn't have?

Not currently, and I probably won't make one. I'm planning to add features as people need them, if it makes sense. We don't need to do everything; just the most useful things.

**Comment by voarsh2** [comment] 2020-12-09 22:00
I am trying to use boring proxy for a simple http tunnel.
But every time I specify port 80, no https I keep getting requests loading over https and obviously the app doesn't look right. Any ideas?

**Comment by anderspitman** [comment] 2020-12-14 17:20
Hey @voarsh2, sorry for the late response. I've been busy working on a related project but haven't been focusing on boringproxy at the moment. I believe the problem you're seeing is caused by the boringproxy server redirecting all requests on port 80 to port 443. The reason it works this way is because I don't see much use in unencrypted HTTP. Plus a primary purpose of boringproxy is to provide automatic HTTPS in front of services that don't provide it. Is there a reason you need port 80? If you can describe your use case more we can discuss and determine if it makes sense to add this functionality.

**Comment by anderspitman** [comment] 2021-01-13 14:43
Closing for now. Feel free to reach out if you have more details.

**Closed by anderspitman** 2021-01-13 14:43 UTC

**Comment by matbgn** [comment] 2022-09-29 12:52
Hi @anderspitman I just came accross this issue as this is still an... Issue for me and I also think for person in general who would like to jump in self-hosting world.

You asked:
> Is there a reason you need port 80? If you can describe your use case more we can discuss and determine if it makes sense to add this functionality.

To have more details, you can simply look at our discussion on the forum:

https://forum.indiebits.io/t/feature-proposal-wild-card-forwarding-on-a-subdomain-80-443-traffic-e-g-with-caprover/106

It
