### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by voarsh2** [boringproxy/boringproxy#34] opened 2021-01-10 14:51 UTC
Anyone seen this issue?

![image](https://user-images.githubusercontent.com/60437695/104126223-58ac2600-5353-11eb-8474-91728677efe6.png)

**Comment by voarsh2** [comment] 2021-01-10 15:41
I increased the limit, I didn't find this was necessary when using NGROK.

**Comment by anderspitman** [comment] 2021-01-11 17:13
I've never seen that. Could be caused by a lot of things. If it's a bug in boringproxy hopefully me or another developer will run into it so we can debug it.

**Comment by voarsh2** [comment] 2021-01-11 17:16
Hmm.
Not sure why it happened. Other services didn't give me this issue.
Raising limits is the only solution right now.
________________________________

**Comment by anderspitman** [comment] 2021-01-11 17:19
Given the number of issues you're having with the boringproxy beta, it sounds like you might be better served using ngrok or something similar for now. boringproxy is really at the stage where it's usable by developers if they're willing to do a little debugging, but I simply don't have the time to recreate everyone environment to debug specific issues. I expect to encounter most serious bugs myself eventually, and fix them as I do, but there's no telling how long that can take for any specific bug.

**Comment by anderspitman** [comment] 2021-01-19 00:06
Closing for now. Let me know if you find any more details about what causes this.

**Closed by anderspitman** 2021-01-19 00:06 UTC

**Comment by derwaldgeist** [comment] 2022-02-24 15:48
Got the same problem on macOS

**Comment by anderspitman** [comment] 2022-02-24 17:59
Hey @derwaldgeist, thanks for the report. Is this happening on the client or server?
