### ISSUE TITLE
Failure obtaining certificate

### ISSUE THREAD

**Issue by RJDavison** [boringproxy/boringproxy#97] opened 2021-08-30 08:27 UTC
After running the command: ./boringproxy-linux-amd64 server'and inputting my ddns domain (provided by no-ip), Im receiving the following error:

2021/08/30 09:23:45 brng.hopto.org: obtaining certificate: [brng.hopto.org] Obtain: [brng.hopto.org] solving challenges: brng.hopto.org: no solvers available for remaining challenges (configured=[tls-alpn-01] offered=[http-01 dns-01 tls-alpn-01] remaining=[http-01 dns-01]) (order=https://acme-v02.api.letsencrypt.org/acme/order/181125810/20681793860) (ca=https://acme-v02.api.letsencrypt.org/directory)

I've tried a different ddns provider (duckdns) and I'm getting the same output

Any idea what I'm doing wrong.

**Comment by anderspitman** [comment] 2021-08-30 18:14
Can you confirm that the DNS is working properly? If you set up a non-HTTPS webserver (`sudo python3 -m http.server 80`) are you able to open http://brng.hopto.org in your browser?

**Comment by RJDavison** [comment] 2021-09-01 11:10
Yes, the webserver can be accessed from the ddns webaddress

**Comment by anderspitman** [comment] 2021-09-01 15:18
Alright. Can you share the command you're using to start the server?

**Comment by RJDavison** [comment] 2021-09-01 16:19
I'm runinng Ubuntu 21.04

./boringproxy-linux-x86_64 server

it then asks me for the Admin domain. I input it the ddns web address, it pauses for about 4 seconds and then get the output in my original post to this thread.

**Comment by ranjeetrj** [comment] 2021-09-02 13:03
Hey...I am also facing the same issue.

Had you found the solution?

**Comment by anderspitman** [comment] 2021-09-02 20:08
The only other thing I can think of off the top of my head is maybe you have port 443 blocked? Does it work if you run the server like this: `sudo python3 -m http.server 443` and then access it in the browser with `brng.hopto.org:443`?

**Comment by anderspitman** [comment] 2021-09-02 20:13
I just confirmed that I was able to get a fresh set of certs for my personal boringproxy setup, so it's not a change in LetsEncrypt or anything. I'm using a DigitalOcean droplet.

**Comment by ranjeetrj** [comment] 2021-09-03 04:48
The request is coming to the port 443 servers,
But I am not getting the dir list in the browser(Expected output).


![proxyy](https://user-images.githubusercontent.com/65105643/131951908-b75bdd01-a997-4878-a497-22b3f471e771.png)
![boringproxy](https://user-images.githubusercontent.com/65105643/131951910-ee931e53-7c10-4c58-9414-8e38f30c1b60.png)

**Comment by ibeckermayer** [comment] 2021-09-04 19:50
@anderspitman check out https://boringproxy.io/ -- I'm now getting this same error for it (wasn't the case 20 minutes ago)

**Comment by anderspitman** [comment] 2021-09-04 20:46
@ranjeetrj that's not too surprising. Looks like the browser is attempting a TLS connection, which is the default on port 443, even though you explicitly said to use that port.

Unfortunately this means I have no idea what could be wrong with boringproxy. I'd recommend trying to find a more mature project from the list: https://github.com/anderspitman/awesome-tunneling

Cloudflare Tunnel is probably the best option these days. It's a loss leader product for Cloudflare so the free offering is really good.

@ibeckermayer that's concerning. Is it still happening? boringproxy.io is working for me.

**Comment by ibeckermayer** [comment] 2021-09-05 02:05
@anderspitman yes its still happening for me

**Comment by anderspitman** [comment] 2021-09-05 04:13
That is very strange. Can you try a different browser? Are you accessing from the US?

**Comment by ranjeetrj** [comment] 2021-09-06 14:18
Hey @anderspitman 

After adding the tunnel on the server-side. I am getting below error logs on the client-side. 

2021/09/06 19:24:43 BoreTunnel error:  Failed to dial: %!(EXTRA *errors.errorString=ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain)

One more thing I would like to ask:
Do we need to set up DNS ourselves in this client-server setup?

**Comment by ibeckermayer** [comment] 2021-09-07 15:36
@anderspitman something bizarre was going on with my home network. At first I thought it was your tool, since it deals with certificates directly, but then a similar issue began happening for https://getrawmilk.com. I was able to "fix" it by changing to my cellular network (this is Comcast XFINITY in the SF Bay Area).

Anyways, now its working on my home network (as is getrawmilk). I have no idea what was going on, apologies for the red herring.

**Comment by hval007** [comment] 2021-10-17 10:02
@anderspitman I have the same error as described on this thread i.e no solvers available for remaining challenges . My setup is ubuntu 20.04 server on Amazon Lightsail and using namecheap. Thinking I did something wrong I attempted on Linux variant OS in Lightsale including another webpage from a different registerer. 

I would love to get this working instead of looking at alternatives! Also confirmed DNS is working properly as I can setup a HTTPS/Non HTTPS webserver and navigate to my webpage. 

Appreciate if you can tell me what could be going wrong here or if anyone has found a solution to this issue.

**Comment by anderspitman** [comment] 2021-12-03 23:27
Anyone have any luck figuring this out? I'm really not sure what the problem could be based off the information provided.

**Comment by RJDavison** [comment] 2021-12-04 06:40
Yeah, I did. I just made sure port forwarding was properly configured and
it all seemed to work fine

**Comment by anderspitman** [comment] 2021-12-05 18:23
Thanks @RJDavison. I'm going to go ahead an close this. If anyone else feels like there's a deeper cause for their problem, feel free to comment here or open a new issue.

**Closed by anderspitman** 2021-12-05 18:23 UTC
Labels: help wanted

**Comment by ThePresence** [comment] 2021-12-12 16:58
I'm also getting the same error. I've CGNAT connection so port forwarding is not possible.

**Comment by anderspitman** [comment] 2021-12-16 16:44
Hi @ThePresence, the boringproxy server must be accessible from the public internet. Only the clients can be behind NAT. The next version of the server has some code to auto-detect that this is working correctly.
